version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - apt-get install jq -qq -y
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - API_IMAGE_URI=$(jq -r '.ImageURI' $CODEBUILD_SRC_DIR_ApiProductionImageDetails/imagedefinitions.json)
      - docker build --target nginx-prod -t $REPOSITORY_URI:latest --build-arg API_IMAGE_URI=$API_IMAGE_URI .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"api","imageUri":"%s"}{"name":"nginx","imageUri":"%s"}]' $API_IMAGE_URI $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
